export const themeOptions = [
    { label: "VSCode Dark", value: "vs-dark" },
    { label: "Active4D", value: "active4d" },
    { label: "All Hallows Eve", value: "all-hallows-eve" },
    { label: "Amy", value: "amy" },
    { label: "Birds of Paradise", value: "birds-of-paradise" },
    { label: "Blackboard", value: "blackboard" },
    { label: "Brilliance Black", value: "brilliance-black" },
    { label: "Brilliance Dull", value: "brilliance-dull" },
    { label: "Chrome DevTools", value: "chrome-devtools" },
    { label: "Clouds Midnight", value: "clouds-midnight" },
    { label: "Clouds", value: "clouds" },
    { label: "Cobalt", value: "cobalt" },
    { label: "Cobalt2", value: "cobalt2" },
    { label: "Dawn", value: "dawn" },
    { label: "Dracula", value: "dracula" },
    { label: "Dreamweaver", value: "dreamweaver" },
    { label: "Eiffel", value: "eiffel" },
    { label: "Espresso Libre", value: "espresso-libre" },
    { label: "GitHub Dark", value: "github-dark" },
    { label: "GitHub Light", value: "github-light" },
    { label: "GitHub", value: "github" },
    { label: "IDLE", value: "idle" },
    { label: "Katzenmilch", value: "katzenmilch" },
    { label: "Kuroir Theme", value: "kuroir-theme" },
    { label: "LAZY", value: "lazy" },
    { label: "MagicWB (Amiga)", value: "magicwb--amiga-" },
    { label: "Merbivore Soft", value: "merbivore-soft" },
    { label: "Merbivore", value: "merbivore" },
    { label: "Monokai Bright", value: "monokai-bright" },
    { label: "Monokai", value: "monokai" },
    { label: "Night Owl", value: "night-owl" },
    { label: "Nord", value: "nord" },
    { label: "Oceanic Next", value: "oceanic-next" },
    { label: "Pastels on Dark", value: "pastels-on-dark" },
    { label: "Slush and Poppies", value: "slush-and-poppies" },
    { label: "Solarized-dark", value: "solarized-dark" },
    { label: "Solarized-light", value: "solarized-light" },
    { label: "SpaceCadet", value: "spacecadet" },
    { label: "Sunburst", value: "sunburst" },
    { label: "Textmate (Mac Classic)", value: "textmate--mac-classic-" },
    { label: "Tomorrow-Night-Blue", value: "tomorrow-night-blue" },
    { label: "Tomorrow-Night-Bright", value: "tomorrow-night-bright" },
    { label: "Tomorrow-Night-Eighties", value: "tomorrow-night-eighties" },
    { label: "Tomorrow-Night", value: "tomorrow-night" },
    { label: "Tomorrow", value: "tomorrow" },
    { label: "Twilight", value: "twilight" },
    { label: "Upstream Sunburst", value: "upstream-sunburst" },
    { label: "Vibrant Ink", value: "vibrant-ink" },
    { label: "Xcode_default", value: "xcode-default" },
    { label: "Zenburnesque", value: "zenburnesque" },
    { label: "iPlastic", value: "iplastic" },
    { label: "idleFingers", value: "idlefingers" },
    { label: "krTheme", value: "krtheme" },
    { label: "monoindustrial", value: "monoindustrial" }
]