name: Deploy to Juno

on:
    release:
        types: [released]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Install Dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Deploy to Juno
              uses: junobuild/juno-action@main
              with:
                  args: deploy
              env:
                  JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
